---
- name: Install Apache
  hosts: localhost
  tasks:

    - name: install apache
      become: true
      yum:
        name: httpd
        state: present

    - name: change apache to specified port
      become: true
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: 'Listen {{web_port | default(8080) }}'

    - name: Set nis_enabled flag on and keep it persistent across reboots
      become: true
      seboolean:
        name: nis_enabled
        state: true
        persistent: true

    - name: start httpd
      become: true
      service:
        name: httpd
        state: started

    - name: display link to inventory report
      debug:
        msg: "Please go to http://{{hostvars[web_host].ansible_host}}:{{web_port}}"
